#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh arg-one arg-two

Generates expressions

'
    exit
fi

cd "$(dirname "$0")"

main() {
    echo "generating output/expr.rs"
    cargo run --bin generate_ast output
}

main "$@"
